platform: linux

image_resource:
  type: registry-image
  source: { repository: engineerbetter/pcf-ops }

inputs:
  - name: bosh-training-infra
  - name: shared-terraform-state
  - name: students-terraform-state
  - name: student-packs
  - name: director-states

outputs:
  - name: student-packs


params:
  PRIVATE_KEY:
  BASTION_IP:

run:
  path: bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      mkdir -p student-packs/student-packs
      echo "$PRIVATE_KEY" > bastion-key.pem
      chmod 0400 bastion-key.pem
      jq -c '.students[]' students-terraform-state/metadata | while read student; do
          student_name=$( jq -r '.name' <<< "$student" )
          echo "BOSH_ALL_PROXY=\"ssh+socks5://ubuntu@${BASTION_IP}:22?private-key=bastion-key.pem\"" >> .env
          echo "BOSH_CA_CERT=\"$(bosh interpolate director-states/creds-${student_name}.yml --path=/director_ssl/ca)\"" >> .env
          tar -zcvf student-packs/student-packs/${student_name}.tgz bastion-key.pem .env
          rm .env
      done