platform: linux

image_resource:
  type: registry-image
  source: { repository: engineerbetter/pcf-ops }

inputs:
  - name: bosh-training-infra
  - name: shared-terraform-state
  - name: students-terraform-state
  - name: student-packs

outputs:
  - name: student-packs


params:
  PRIVATE_KEY:
  BASTION_IP:

run:
  path: bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      # Create student-packs dir if doesn't exist in bucket 
      mkdir -p student-packs/student-packs
      echo "PRIVATE_KEY=${PRIVATE_KEY}" > student-packs/student-packs/test.env