platform: linux

image_resource:
  type: registry-image
  source: { repository: engineerbetter/pcf-ops }

inputs:
  - name: bosh-training-infra
  - name: students-terraform-state
  - name: student-packs
  - name: director-states

outputs:
  - name: student-packs

params:
  PRIVATE_KEY:

run:
  path: bosh-training-infra/ci/tasks/create-student-packs.sh
