platform: linux

image_resource:
  type: registry-image
  source: { repository: engineerbetter/pcf-ops }

inputs:
  - name: bosh-training-infra
  - name: shared-terraform-state
  - name: students-terraform-state
  - name: student-packs

outputs:
  - name: student-packs


params:
  PRIVATE_KEY:
  BASTION_IP:

run:
  path: bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      mkdir -p student-packs/student-packs

      jq -c '.students[]' students-terraform-state/metadata | while read student; do
          echo "BOSH_ALL_PROXY=\"ssh+socks5://ubuntu@${BASTION_IP}:22?private-key=bastion-key.pem\"" \
            >> student-packs/student-packs/$( jq -r '.name' <<< "$student" ).env
      done