platform: linux

image_resource:
  type: docker-image
  source: {repository: pcf-ops}

inputs:
- name: students-terraform-state
  
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
run:
  path: bash
  args:
    - -xeuc
    - |
    echo "aws version is..."
    aws --version