---
resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: 1.3.4

  - name: multi-file-s3
    type: docker-image
    source:
      repository: 18fgsa/s3-resource-simple
      tag: 1.2.7

resources:
  - name: bosh-training-infra
    type: git
    icon: github
    source:
      uri: https://github.com/EngineerBetter/bosh-training-infra

  - name: bosh-deployment
    type: git
    icon: github
    check_every: 60m
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment

  - name: lab-bosh-deployment
    type: git
    icon: github
    check_every: 60m
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
    version:
      ref: c2430b3ae0509fb2af16996e90b7b14ecb91b438

  - name: lab-cf-deployment
    type: git
    icon: github
    check_every: 60m
    source:
      uri: https://github.com/cloudfoundry/cf-deployment
      branch: main

  - name: lab-spring-music
    type: git
    icon: github
    check_every: 60m
    source:
      uri: https://github.com/EngineerBetter/spring-music
      branch: master

  - name: lab-shared-redis-release
    type: git
    icon: github
    check_every: 60m
    source:
      uri: https://github.com/EngineerBetter/shared-redis-release
      branch: master

  - name: shared-terraform-state
    type: terraform
    icon: terraform
    source:
      backend_type: s3
      env_name: default
      backend_config:
        bucket: ((bucket_name))
        key: terraform/shared
        region: ((region))
        access_key: ((concourse_ci_s3_access_key))
        secret_key: ((concourse_ci_s3_secret_key))

  - name: students-terraform-state
    type: terraform
    icon: terraform
    source:
      backend_type: s3
      env_name: default
      backend_config:
        bucket: ((bucket_name))
        key: terraform/students
        region: ((region))
        access_key: ((concourse_ci_s3_access_key))
        secret_key: ((concourse_ci_s3_secret_key))

  - name: director-states
    type: s3
    source:
      bucket: ((bucket_name))
      region_name: ((region))
      versioned_file: director-states/states.tgz
      initial_version: "0"
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))

  - name: student-packs
    type: multi-file-s3
    source:
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))
      bucket: ((bucket_name))
      change_dir_to: student-packs
      region: ((region))
      options:
        - "--only-show-errors"
        - "--exclude '*'"
        - "--include 'student-packs/*.tgz'"

jobs:
  - name: set-pipeline
    plan:
      - get: bosh-training-infra
        trigger: true
      - set_pipeline: training-infra
        file: bosh-training-infra/ci/pipeline.yaml
        var_files: [bosh-training-infra/vars.yaml]

  - name: terraform-shared
    serial: true
    serial_groups: [infrastructure]
    plan:
      - get: bosh-training-infra
        passed: [set-pipeline]
        trigger: true
      - put: shared-terraform-state
        params:
          terraform_source: bosh-training-infra/terraform/shared
          vars:
            region: ((region))
            cs_office_ip: ((cs_office_ip))
            key_name: ((key_name))
            availability_zone: ((region))a
            public_key: ((bosh-training-key.public_key))
            eb_ci_nat_gateway: ((eb_ci_nat_gateway))
          env:
            AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
            AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))

  - name: delete-student-envs
    serial: true
    serial_groups: [bosh-director]
    plan:
      - in_parallel:
          - get: bosh-training-infra
            trigger: true
            passed: [terraform-shared]
          - get: bosh-deployment
          - get: director-states
            params: { unpack: true }
          - get: shared-terraform-state
          - get: students-terraform-state
      - load_var: shared-terraform-outputs
        file: shared-terraform-state/metadata
        format: json
      - task: delete-envs
        file: bosh-training-infra/ci/tasks/delete-envs.yaml
        params:
          AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
          AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
          DEFAULT_KEY_NAME: ((key_name))
          PRIVATE_KEY: ((bosh-training-key.private_key))
        ensure:
          do:
            - task: compress-state
              file: bosh-training-infra/ci/tasks/compress.yaml
              input_mapping: { target: director-states }
              vars: { files: creds-*.yml state-*.json }
            - put: director-states
              params: { file: compressed/archive.tgz }
              get_params: { unpack: true }

  - name: terraform-students
    serial: true
    serial_groups: [infrastructure]
    plan:
      - in_parallel:
          - get: bosh-training-infra
            passed: [delete-student-envs]
            trigger: true
          - get: shared-terraform-state
          - get: students-terraform-state
            params:
              output_planfile: true
      - load_var: shared-terraform-outputs
        file: shared-terraform-state/metadata
        format: json
      - put: students-terraform-state
        params:
          terraform_source: bosh-training-infra/terraform/students
          vars:
            region: ((region))
            vpc_id: ((.:shared-terraform-outputs.vpc_id))
            security_group_id: ((.:shared-terraform-outputs.security_group_id))
            availability_zone: ((region))a
          var_files: [bosh-training-infra/students.auto.tfvars.json]
          env:
            AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
            AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))

  - name: create-student-envs
    serial: true
    serial_groups: [bosh-director]
    plan:
      - in_parallel:
          - get: bosh-deployment
          - get: bosh-training-infra
            trigger: true
            passed: [terraform-students]
          - get: students-terraform-state
          - get: shared-terraform-state
          - get: director-states
            params: { unpack: true }
      - load_var: shared-terraform-outputs
        file: shared-terraform-state/metadata
        format: json
      - task: create-envs
        file: bosh-training-infra/ci/tasks/create-envs.yaml
        params:
          AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
          AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
          DEFAULT_KEY_NAME: ((key_name))
          PRIVATE_KEY: ((bosh-training-key.private_key))
        ensure:
          do:
            - task: compress-state
              file: bosh-training-infra/ci/tasks/compress.yaml
              input_mapping: { target: director-states }
              vars: { files: creds-*.yml state-*.json }
            - put: director-states
              params: { file: compressed/archive.tgz }
              get_params: { unpack: true }

  - name: create-student-packs
    serial: true
    plan:
      - in_parallel:
          - get: bosh-training-infra
            trigger: true
            passed: [create-student-envs]
          - get: director-states
            params: { unpack: true }
          - get: shared-terraform-state
          - get: students-terraform-state
          - get: student-packs
      - load_var: shared-terraform-outputs
        file: shared-terraform-state/metadata
        format: json
      - task: create-packs
        file: bosh-training-infra/ci/tasks/create-student-packs.yaml
        params:
          PRIVATE_KEY: ((bosh-training-key.private_key))
      - put: student-packs

  - name: test-labs
    serial: true
    plan:
      - in_parallel:
          - get: bosh-training-infra
            passed: [create-student-packs]
          - get: student-packs
          - get: lab-bosh-deployment
          - get: lab-cf-deployment
          - get: lab-spring-music
          - get: lab-shared-redis-release
      - task: setup-lab
        file: bosh-training-infra/ci/tasks/setup-lab.yaml
      - task: test-lab1
        file: bosh-training-infra/ci/tasks/test-lab1.yaml
      - task: test-lab3
        file: bosh-training-infra/ci/tasks/test-lab3.yaml
      - task: test-lab4
        file: bosh-training-infra/ci/tasks/test-lab4.yaml
        params:
          SHARED_REDIS_SHA: af48020

  - name: cleanup-test-director
    serial: true
    plan:
      - in_parallel:
          - get: bosh-training-infra
            passed: [create-student-packs]
          - get: student-packs
      - task: setup-lab
        file: bosh-training-infra/ci/tasks/setup-lab.yaml
      - task: test-cleanup
        file: bosh-training-infra/ci/tasks/test-cleanup.yaml
