---
# resource_types:
# - name: terraform
#   type: docker-image
#   source:
#     repository: ljfranklin/terraform-resource
#     tag: 1.2.2

resources:
- name: bosh-training-infra
  type: git
  icon: github
  source:
    uri: https://github.com/EngineerBetter/bosh-training-infra

jobs:
- name: set-pipeline
  plan:
  - get: bosh-training-infra
    trigger: true
  - set_pipeline: training-infra
    file: bosh-training-infra/ci/pipeline.yaml
- name: hello
  plan:
  - get: bosh-training-infra
    passed: [set-pipeline]
    trigger: true
  - task: hello
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello, World!"]