---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 1.2.3

resources:
- name: bosh-training-infra
  type: git
  icon: github
  source:
    uri: https://github.com/EngineerBetter/bosh-training-infra

- name: shared-terraform-state
  type: terraform
  icon: terraform
  source:
    backend_config:
      bucket: ((bucket_name))
      key: terraform/shared
      region: ((region))
      access_key: ((concourse_ci_s3_access_key))
      secret_key: ((concourse_ci_s3_secret_key))

jobs:
- name: set-pipeline
  plan:
  - get: bosh-training-infra
    trigger: true
  - set_pipeline: training-infra
    file: bosh-training-infra/ci/pipeline.yaml
    var_files: [bosh-training-infra/vars.yaml]

- name: terraform-shared
  plan:
  - get: bosh-training-infra
    passed: [set-pipeline]
    trigger: true
  - put: shared-terraform-state
    params:
      terraform_source: bosh-training-infra/terraform/shared
      vars: { region: ((region)) }
