platform: linux

image_resource:
  type: registry-image
  source: { repository: engineerbetter/pcf-ops }

inputs:
  - name: bosh-training-infra
  - name: director-states
  - name: students-terraform-state

params:
  PRIVATE_KEY:
  BASTION_IP:
  BOSH_CLIENT: admin
  BOSH_NON_INTERACTIVE: true

run:
  path: bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      echo "$PRIVATE_KEY" > key.pem
      chmod 0400 key.pem

      export BOSH_ALL_PROXY="ssh+socks5://ubuntu@${BASTION_IP}:22?private-key=key.pem"

      jq -c '.students[]' students-terraform-state/metadata | while read student; do
        student_name="$( jq -r '.name' <<< "$student" )"
        certs="$( printf "%s\n%s" "$( bosh interpolate "director-states/creds-${student_name}.yml" --path /director_ssl/certificate )" "$( bosh interpolate "director-states/creds-${student_name}.yml" --path /uaa_ssl/certificate )" )"

        bosh \
          update-runtime-config \
          --client-secret="$( bosh interpolate "director-states/creds-${student_name}.yml" --path /admin_password )" \
          --environment="$( jq -r '.internal_ip' <<< "$student" )" \
          --ca-cert="$certs" \
          bosh-training-infra/runtime-config.yaml
      done
